apiVersion: apps/v1
kind: Deployment
metadata:
  name: clip-weaviate-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clip-weaviate-ui
  template:
    metadata:
      labels:
        app: clip-weaviate-ui
    spec:
      containers:
      - name: clip-weaviate-ui
        image: waggle/clip-weaviate-ui:latest
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 1Gi
        ports:
        - containerPort: 5000
        env:
        - name: WEAVIATE_API
          value: "http://weaviate:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: clip-weaviate-ui
spec:
  type: LoadBalancer
  ports:
  - name: web-api-interface
    port: 5000
    targetPort: 5000
  selector:
    app: clip-weaviate-ui