apiVersion: apps/v1
kind: Deployment
metadata:
  name: clip-weaviate-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clip-weaviate-ui
  template:
    metadata:
      labels:
        app: clip-weaviate-ui
    spec:
      containers:
      - name: clip-weaviate-ui
        image: waggle/clip-weaviate-ui:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1
            memory: 50Mi
          limits:
            cpu: 2
            memory: 1Gi
        ports:
        - containerPort: 7860
        env:
        - name: WEAVIATE_API
          value: "http://weaviate:8080"
        - name: CLUSTER_FLAG
          value: "True"
---
apiVersion: v1
kind: Service
metadata:
  name: clip-weaviate-ui
spec:
  type: LoadBalancer
  ports:
  - name: web-api-interface
    port: 7860
    targetPort: 7860
  selector:
    app: clip-weaviate-ui