apiVersion: apps/v1
kind: Deployment
metadata:
  name: CLIP-App
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CLIP-App
  template:
    metadata:
      labels:
        app: CLIP-App
    spec:
      containers:
      - name: clip-weaviate-ui
        image: waggle/clip-weaviate-ui:latest
        resources:
          requests:
            cpu: 50m
            memory: 25Mi
          limits:
            cpu: 75m
            memory: 50Mi
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: clip-weaviate-ui
spec:
  selector:
    app: clip-weaviate-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
