apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
      - name: weaviate
        image: semitechnologies/weaviate:1.23.10
        command:
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "8080"
        - "--scheme"
        - "http"
        ports:
        - containerPort: 8080
        - containerPort: 50051
        env:
        - name: CLIP_INFERENCE_API
          value: "http://multi2vec-clip:8080"
        - name: QUERY_DEFAULTS_LIMIT
          value: "25"
        - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
          value: "true"
        - name: PERSISTENCE_DATA_PATH
          value: "/var/lib/weaviate"
        - name: DEFAULT_VECTORIZER_MODULE
          value: "multi2vec-clip"
        - name: ENABLE_MODULES
          value: "multi2vec-clip"
        - name: CLUSTER_HOSTNAME
          value: "node1"
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate
spec:
  selector:
    app: weaviate
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 50051
      targetPort: 50051